name: Scancode
'on':
- pull_request
jobs:
  scancode_job:
    runs-on: ubuntu-latest
    name: Scan code for licenses
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Scan the code
      id: scancode
      uses: zephyrproject-rtos/action_scancode@v4
      with:
        directory-to-scan: scan/
    - name: Artifact Upload
      uses: actions/upload-artifact@v3
      with:
        name: scancode
        path: ./artifacts
    - name: Verify
      run: "if [ -s ./artifacts/report.txt ]; then\n  report=$(cat ./artifacts/report.txt)\n\
        \  report=\"${report//'%'/'%25'}\"\n  report=\"${report//$'\\n'/'%0A'}\"\n\
        \  report=\"${report//$'\\r'/'%0D'}\"\n  echo \"::error file=./artifacts/report.txt::$report\"\
        \n  exit 1\nfi\n"
